- README.md
> Delete unnecessary space

- .jshintrc
Unified the JavaScript coding style.
> JavaScript coding style refactor

- perf/benchmark.js
This PR enable to take correct benchmark. :smile:
Please review it.
> fix(benchmark): fix to enable to use second argument version

- lib/async.js
- test/test-async.js
> Queue concurrency

- lib/async.js
Hi, there are some 2 space and 4 space at the same time. So I covert these 2 space to 4.
> covert some 2 space to 4

- README.md
I'm not entirely sure what the original intention was so the fix should be reviewed first... but I think that this is what was meant
> Fix timesSeries documentation

- lib/async.js
> Implement _reject via _filter

- test/test-async.js
Doing this made me question my sanity, but nonetheless, this should help to prevent some timeout errors in the future :)
> Add expect statements to (many) tests

- .npmignore
- package.json
Also drops some unneeded files from npm releases
> Chore: Update dev dependencies

- README.md
- lib/async.js
- test/test-async.js
It's basically `whilst` and `doWhilst` with async truth test.
Addresses #156 #602 
Will add documentation if maintainer is okay with this PR.
> during & doDuring with async test

- lib/async.js
This should also be an optimization as it avoids a lot of the function creation overhead associated with the current implementation.
> Implement doDuring via during

- lib/async.js
This is both an optimization (avoid restParam + concat) and a code simplification :D
> Optimize applyEach* via creator function

- lib/async.js
As I mentioned in the #828 pull request, this is easy to extend to `_detect`. Also should `detectLimit` be added?
> Implement _detect via tester

- lib/async.js
> once: ensure fn is gced

- CHANGELOG.md
diff: https://github.com/caolan/async/compare/v1.3.0...master
Feel free to submit changes to this branch directly
> Update CHANGELOG.md for v1.4

- lib/async.js
- test/test-async.js
This function is already in the documentation but was not in the implementation.
> Add detectLimit

- dist/async.js
> Revert "Implement eachOf via keyIterator"

- README.md
as the example is using setImmediate, not nextTick
> update docs to reflect setImmediate in example

- lib/async.js
- test/test-async.js
> Implement eachOf through _keyIterator

- lib/async.js
- test/test-async.js
> Bug fix #945 - Pause in queue with concurrency doesn't pause

- lib/async.js
- test/test-async.js
> auto stops after error #988

- lib/async.js
I had to put this change in to spot where my typo was, so thought I would make a PR
> Add some information to error message

- README.md
> readme fix after last change

- mocha_test/queue.js
Related to https://github.com/caolan/async/pull/1030
3rd test case doesn't correct.
After pushing, worker will be called.
> fix queue test

- lib/auto.js
- mocha_test/auto.js
> Defend against multiple callbacks in auto

- lib/retry.js
- mocha_test/retry.js
- test/test-async.js
Closes #941 .  I also want to separate out the old "control flow" decorator behavior into another method.
> Make callback optional in retry

- .github/ISSUE_TEMPLATE.md
> Add a issue template for users filing new issues

- Makefile
Now works on OS X (tested 10.11.4), sed -E should work on linux, not tested..
> Fix Makefile build on OS X

- lib/timeout.js
Boring/pedantic PR is boring/pedantic
> Fix misspelling of "milliseconds"

- support/jsdoc/jsdoc-custom.css
Sorry @aearly, I just pushed a quick fix to the branch when you were merging it. I accidentally undid one of @megawac 's CSS fixes in one of my commits. There is his fix for it to ensure the entire toc table is visible.
> quick toc fix for static site

- lib/reflectAll.js
- mocha_test/parallel.js
I made this PR for solve this issue #1195 
```
let tasks = {
one: function(callback) {
setTimeout(function() {
callback(null, 'one');
}, 200);
},
two: function(callback) {
callback('two');
},
three: function(callback) {
setTimeout(function() {
callback(null, 'three');
}, 100);
}
};
async.parallel(async.reflectAll(tasks),
// optional callback
function(err, results) {
// values
// results.one.value = 'one'
// results.two.error = 'two'
// results.three.value = 'three'
});
```
If you have any feedback just let me know, thanks.
> ReflectAll allow to accept object of functions

- lib/reflectAll.js
Fixes of #1207 
@megawac's suggestions
> ReflectAll, use lodash functions instead native functions

- lib/retry.js
- mocha_test/retry.js
Also makes the retry code much simpler (and probably faster)
> Fixes #1226, make retry interval asynchronous

- lib/priorityQueue.js
- mocha_test/priorityQueue.js
Related #1229
If `priority` wasn't defined, `undefined >= undefined` is false.
What do you think about default value?
I'm not sure which is better 0 or 1.
> fix execution order

- karma.conf.js
- mocha_test/asyncify.js
- mocha_test/forever.js
- mocha_test/nextTick.js
- mocha_test/parallel.js
- mocha_test/series.js
- mocha_test/support/is_browser.js
- mocha_test/waterfall.js
Removes browser checks in tests.  Fixes asyncify promisified to run in browser (fixes #1235)
> Use mocha tag for non-browser tests, fix asyncify promisified browser tests

- lib/doWhilst.js
> Documentation typo

- docs.html
- lib/eachLimit.js
> Fix misspelled word

- lib/race.js
> Minor typo fix

- mocha_test/queue.js
- mocha_test/retry.js
http://mochajs.org/#retry-tests
The tests that I've added retries to are ones I've noticed fail intermittently (especially queue.pause). Let me know if any others should be added
(#1322)
> Retry flaky tests several times when they fail

- lib/internal/filter.js
fyi @CodeMan99 
```
Latest tag is  v2.1.2
Comparing v2.1.2 with current on Node v6.2.2
--------------------------------------
filter(10) v2.1.2 x 45,704 ops/sec ±6.87% (27 runs sampled), 0.0219ms per run
filter(10) current x 53,959 ops/sec ±1.74% (29 runs sampled), 0.0185ms per run
current is faster
--------------------------------------
filter(300) v2.1.2 x 3,978 ops/sec ±7.62% (30 runs sampled), 0.251ms per run
filter(300) current x 5,290 ops/sec ±2.40% (30 runs sampled), 0.189ms per run
current is faster
--------------------------------------
filter(10000) v2.1.2 x 74.95 ops/sec ±5.52% (26 runs sampled), 13.3ms per run
filter(10000) current x 108 ops/sec ±2.91% (31 runs sampled), 9.30ms per run
current is faster
--------------------------------------
filterLimit(10) v2.1.2 x 46,619 …
```
> Implement array specific filter function

- README.md
Closes https://github.com/caolan/async/issues/1362
> Added libhive badge to README

- lib/internal/DoublyLinkedList.js
- mocha_test/queue.js
- mocha_test/retry.js
Related: #1322 
I completely re-did that notorious `queue.pause` test.  I also tweaked the flakey retry test, so it might give more clues in the future when it fails.
> Hopefully fix flakey tests

- README.md
put an https link in readme.md to avoid the browser from producing a SSL warning
> https link in readme.md

- lib/tryEach.js
I believe a small mistake was in the tryEach docs.
> Fix tryEach documentation code example

- Makefile
2018 oss contributions fulfilled :heavy_check_mark:
> Typo in makefile comment

- lib/queue.js
need to demonstrate to users how to use a single error callback
> need to demonstrate error cb not just drain cb

- lib/asyncify.js
- test/asyncify.js
> [issue-1568][bug]: make sure error object defined before access its message

- lib/queue.js
Just a little thing I noticed :)
> sentence fix

- lib/retry.js
- test/retry.js
> fix: send proper retry count to retry's interaval func

- lib/whilst.js
- test/whilst.js
Really minor change, but I figured it would be good to get a second set of eyes, at least on the test. Thanks!
> initialize results in whilst [fixes #1626]

- lib/reflect.js
- test/es2017/asyncFunctions.js
- test/parallel.js
- test/series.js
> fix: Reflect passes value on error

- README.es.md
- README.md
That site is dead, the badge can be removed
> Remove libhive badge from Readme

- lib/internal/awaitify.js
Solves https://github.com/caolan/async/issues/1700
> Allow redefining name property in awaitable

- dist/async.js
- docs/v3/docs.html
- docs/v3/module-ControlFlow.html
- docs/v3/queue.js.html
- docs/v3/scripts/async.js
- lib/queue.js
Thanks for the great work on this library!
> Fix typo in queue examples

- test/detect.js
> chore: Fix typo in detect.js

- lib/internal/consoleFunc.js
- test/each.js
- test/priorityQueue.js
- each
- priorityQueue
- consoleFunc
> Improving  tests case coverage

- intro.md
Hello,
As I saw that you maintain a list of libraries that are alternatives or complements to Async.js, I would like to propose the one I released recently.
Everything is on the npm page: https://www.npmjs.com/package/modern-async
Thanks in advance for your answer.
> Added modern-async to the list of other libraries

- .azure-pipelines-steps.yml
- .azure-pipelines.yml
- package-lock.json
- package.json
> chore: remove manual coveralls execution

- karma.conf.js
- package-lock.json
- package.json
The old Edge is EOL now and this wasn't working on CI
> chore: remove karma-edge-launcher

- package-lock.json
- package.json
The latest version of babel-core was 5 years ago and this package uses that version of babel/core. I upgraded to the new version @babel/core.
https://www.npmjs.com/package/babel-core
https://www.npmjs.com/package/@babel/core
> chore: updated babel/core to @babel/core
