README.md
lib/async.js
test/test-async.js

This is mostly @dominicbarnes 's work from #168.  The last missing piece was documentation, which I added.  I also made sure it merges with what is currently on master, and simplified the logic in one place.

Completing forEachOf

---

lib/async.js
test/test-async.js

So, I needed the ability to iterate objects (and get the `key` passed into the iterator) and noticed it was not done because it would break compatibility with the Node.js standard libs. I am proposing this "convention" of adding the `Of` suffix on iterators that deal with objects. (instead of arrays)
If this entire concept is rejected outright, then I'll stop here. However, if this seems like a good idea/convention I can finish up adding the same concept to the other various collection iterators.
Usage:
async.forEachOf({ a: 1, b: 2 }, function (value, key, callback) {
// value = 1, 2
// key   = a, b
}, function (err) {
// complete
});

Adding forEachOf to Iterate Objects

---

lib/async.js

I'm using Require.js, so `this` doesn't refer to the `window` object, so async didn't work until I made this change.

Better support for require.js

---

README.md

Minor fix for a typo in the documentation for `memoize()` arguments

Correct spelling of 'An'

---

README.md

to match `applyEach` so it's not confusing what it does

Update `applyEachSeries` function signature

---

README.md
lib/async.js

This is my understanding of the default hash function of async.memoize, which isn't currently documented. Hopefully it will be accepted or corrected. Either way, I learn if I'm right!
There are three commits because github can't quite figure out I backed out an older pull request of mine, but the diff is clean.

Document behavior of the default hash function of async.memoize

---

Makefile

Basically, the make tasks break if your current working directory contains spaces. This PR wraps the cwd in quotes so that doesn't happen.

Wrap makefile directory strings in quotes

---

README.md

Updated source to download `async.js`, as well as adding method to install via `bower`.

Updating download section

---

lib/async.js

I fixed not to use `Array.prototype.slice.call(arguments)`.
This `_baseSlice` is based on [lodash](https://github.com/lodash/lodash/blob/master/lodash.src.js#L2711-L2731).
- [improve performance](https://github.com/suguru03/neo-async/commit/be3997f2c94baa82b1f839c4e25a0c60c5103f91)
- [Optimiztion-killers#leaking-arguments](https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#32-leaking-arguments)

perf(slice): fix not to use `Array#slice`

---

README.md

For some reason the README only included one of @rhyzx 's brilliant animations, which really help explain `cargo`

Add cargo animation to README

---

lib/async.js
test/test-async.js

Solved issue described in https://github.com/caolan/async/issues/649

Fixed issue with _eachLimit continuing to run after error

---

.gitignore
.travis.yml
README.md
package.json

This adds a coverage report badge using coveralls.io, and the nyc bin.
* `run npm run coverage` to get a human readable coverage report.
* `run npm run coverage -- --reporter=lcov` to get an HTML report over coverage in the /coverage folder.
* run npm run coveralls to report coverage to the coveralls.io. make sure you set the `COVERALLS_REPO_TOKEN`.
* setup a token here: https://coveralls.io

adds coveralls coverage reports using nyc

---

README.md
lib/async.js
perf/benchmark.js
perf/suites.js
test/test-async.js

Adds a new utility function for wrapping async functions.  It ensures that the function always calls is callback on a later tick in the event loop.  I'm also considering using this function internally to prevent stack overflows with synchronous iteration functions.

ensureAsync

---

README.md

This change wraps `seq(fn1, fn2...)`'s arguments doc in backticks to match the rest of the doc.

Wrap seq arguments doc in backticks

---

.jshintrc
lib/async.js

Refer to https://github.com/jashkenas/underscore/issues/2152. We were using a similar approach to `async`s current one in underscore until https://github.com/jashkenas/underscore/pull/2153.
The two main benefits of this change are:
- Forwards compatibility with `strict` mode and some tooling (see https://github.com/jashkenas/underscore/issues/2152)
- `WebWorker` support, you can't use `window` in a `WebWorker` but you can use `self`
Aside: [here's the detection method from lodash](https://github.com/lodash/lodash/blob/master/lodash.js#L248-254)

Improve the detection of global/root object

---

lib/async.js

This has been known to greatly simplify code (heavily used in underscore and lodash) and be a great optimization (slicing arguments is sloooooooooooow).
If interested, refer to these threads for documentation, benchmarks, arguments, naming, etc:-)
- https://github.com/jashkenas/underscore/pull/2140
- https://github.com/lodash/lodash/issues/1122
- https://lodash.com/docs#restParam

Replace slice with restParam

---

lib/async.js

This seems to have been missed in all the `_parallel` changes

Implement series via _parallel

---

README.md
lib/async.js
package.json
perf/suites.js
test/test-async.js

Merges the implementations of `some` and `every` and adds their respective limit functions (with partial short circuiting)
PS I think short circuiting should be done like lodash does it (allowing `each` to break):
if `cb` resolves with `cb(false)` you break the loop (in lodash if you return false it breaks the loop)
Resolves #548

Add someLimit and everyLimit

---

.jscsrc
Makefile
lib/async.js
package.json
perf/benchmark.js
perf/memory.js
perf/suites.js
test/test-async.js

Wheewh :weary: I need :coffee: 
Stricter rules (e.g. google or airbnb style guide) should probably follow

Implement style guide check via jscs

---

lib/async.js
package.json
test/test-async.js

Most of Promise realisations doesn't contain `nodeify` method. Here is extention of async wrapper for promisified functions.
For example promise-styled [openpgp](https://github.com/openpgpjs/openpgpjs) library functions looks like
```javascript
openpgp.key.generate(options).then(function(key) {
// success
}).catch(function(error) {
// failure
});
```
And can be easily wrapped to use with favourite async:)
```javascript
async.asyncify(openpgp.key.generate);
```

asyncify promisified functions

---

dist/async.js

The main advantage of this is if we plan further refactors (#839, #847)
Can't believe this worked in one try (:D)

Implement eachOf via keyIterator

---

README.md

Consistent with first use on line 10 and the accepted spelling.

adds caps to spelling of JavaScript

---

README.md

Corrects 'embeded' to 'embedded'

Fixes a typo in the Readme

---

lib/async.js

Reminded of this by #903
This probably justifies a patch release... previously on gitter
> **joystick** Now I'm facing some (node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
**megawac** hey @joystick I think you may of found a bug/inconsistency. Want to submit a pull request to the repo changing async.nextTick to async.setImmediate?
**joystick** @megawac I'm not yet ready for PR submission, since I don't know how to fix this. But I will collect info to reproduce the case. This issue is about iterating over array of 1k to 20k elements. Iterator make call to SAP server to find account data information. When I limit array to 200-500 elements no warning issued. if 1k+ I receive warnings about …

Use setImmediate consistently over nextTick

---

lib/async.js
test/test-async.js

Map currently will attempt to assign keys to arrays and because of a bug in `nodeunit` this passes unit tests. I think map should either always return an array (ala lodash/underscore) for objects or do as this PR does
/cc @aearly

Allow map to return objects

---

lib/async.js
test/test-async.js

Similar concept to https://lodash.com/docs#transform this is a function with several fundamental differences to async.reduce:
- parallel
- dynamically interprets memo (signature arr|obj, arr|obj, fn, fn -> arr|obj) which can be useful for recursive cases
- provides key to iterator function

Add async.transform

---

README.md
lib/async.js
test/test-async.js

Adds an argument to `async.auto` to specify maximum concurrency with which to run tasks.
Fixes #635.

Add concurrency argument to async.auto

---

README.md
lib/async.js
test/test-async.js

Addresses https://github.com/caolan/async/issues/962

pass last result to while/until callback

---

README.md

Minor change in Readme for `async.every()` to mention that not every iterator will run if one of them returns a falsy value (copy-pasted wording from `async.some()`).

Bug fix #968: uddate Readme for `async.every()`

---

lib/async.js
test/test-async.js

async.auto({....}, 5); -> "fn.apply is not a function"

Incorrect handling of arguments in "auto" in case of empty callback

---

lib/async.js

Inexistant is not a commonly used English word.

Use `nonexistent` instead of `inexistant` in error message.

---

lib/async.js
test/test-async.js

when key is "constructor", method after memoized will return "undefined" immediately.
```js
var async = require('async');
var hardAsyncMethod = function(name, callback){
setTimeout(function(){
callback(null, 'hello, ' + name);
}, 5000);
};
var memoizedHardAsyncMethod = async.memoize(hardAsyncMethod);
memoizedHardAsyncMethod('normalString', function(error, results){
// normal process
console.log(error);
console.log(results);
});
memoizedHardAsyncMethod('constructor', function(error, results){
// will return undefine immediately
console.log(error);
console.log(results);
});
```

prevent return "undefined" immediately when key is "constructor" for memoize method

---

package.json

https://github.com/caolan/async/issues/916
The wildcards are not necessary and causes sadness for Windows users.

Fix Lint for Windows by removing unnecessary wildcarding

---

README.md

Hi!
Here is some doc style inconsistency fixes.
The bigger one is about 2 and 4 spaces as an identation.
The second is about anchors - this kind of html urls can't be parsed via commonmark parser (I used it to generate [Dash docset for Async.js](https://github.com/Kapeli/Dash-User-Contributions/tree/master/docsets/Async.js)), so I fixed it.
And a little one - I removed `detectSeries` link from `detect` cause it doesn't exists.

docs style consistency

---

README.md
lib/internal/createTester.js
lib/internal/filter.js
lib/internal/reject.js
test/test-async.js

@megawac 
#774 but against modularization branch

filter, reject, detect, some, every with error

---

lib/priorityQueue.js
mocha_test/priorityQueue.js

Related to https://github.com/caolan/async/pull/1030
I fixed `priorityQueue`.
It has `unsaturated` params but it doesn't work.
Could you check this PR?

add unsaturation event to `priorityQueue`

---

README.md
lib/index.js
lib/race.js
mocha_test/race.js

Based on the discussion from #568 .
Contains mocha-based tests and readme update.
Same as #1018 but using modules.

async.race module

---

lib/each.js
lib/eachOf.js
lib/eachOfSeries.js
lib/eachSeries.js
lib/every.js
lib/filter.js
lib/filterSeries.js
lib/internal/doLimit.js
lib/map.js
lib/mapSeries.js
lib/parallel.js
lib/reject.js
lib/rejectSeries.js
lib/some.js
lib/times.js
lib/timesSeries.js
test/test-async.js

@aearly @megawac 
fixes #778
Ended up adding `concatLimit` and `detectLimit` in the process. 
Still need to add tests and documentation

implement <name> and <name>Series with <name>Limit

---

lib/index.js
lib/timeout.js
mocha_test/timeout.js
test/test-async.js

Implements timeout feature discussed in #1007. 
Follows @aearly advice on using a wrapper around the asynchronous functions. I changed the function arguments' order to match ```setTimeout``` signature.
If there are any mistakes or things that need modification, just let me know.
I can add the readme info if this looks good.

Support function timeout via async.timeout wrapper

---

README.md~

Updates README with instructions on how to use `async.timeout` (added in #1027).

Add entry for async.timeout in README

---

lib/constant.js
mocha_test/constant.js

Add support for dynamic arguments in constant(), references issue #1016.

Support dynamic arguments in async.constant (ref. #1016)

---

README.md
lib/internal/setImmediate.js
lib/nextTick.js
mocha_test/nextTick.js
mocha_test/setImmediate.js
test/test-async.js

Pass extra args to setImmediate/nextTick.  

---

README.md
lib/autoInject.js
lib/index.js
mocha_test/autoInject.js

This is adapted from the code in #608.

autoInject

---

lib/auto.js
mocha_test/auto.js

Related to #696 
I had to completely rework things.  Auto should be a bit more efficient now for complicated workflows as well.
This does change execution order slightly, but it's still correct behavior.

Refactor auto to not need a deferral

---

README.md

See https://github.com/caolan/async/pull/1060 - either that one is correct or this one is.  Cannot both be true.

update readme - iteratee - callback(null, truthValue)

---

lib/asyncify.js
lib/constant.js
lib/ensureAsync.js
lib/internal/applyEach.js
lib/internal/initialParams.js
lib/memoize.js
lib/retryable.js
lib/timeout.js

A minor internal tweak.  It introduces a new internal function -- `initialParams` -- analagous to `rest`, except it always passes 2 args to the wrapped function -- the intial args and the last arg (usually the callback).  It saves a few lines of code.

Use "initialParams" internally to simplify getting callbacks

---

README.md
lib/index.js
lib/reflect.js
lib/reflectAll.js
test/test-async.js

This is the new PR for the reflect for 2.0 (https://github.com/caolan/async/pull/1012). I change the branch because of the big changes to files.

Add back reflect and reflectAll.

---

README.md

http://spmjs.io/ has shut down but the readme link remains

Removed SPM from readme as it is dead

---

Makefile

Manually setting the source map URL in the `Makefile`,as when `--source-map` is specified without `--source-map-url`, the source map URL defaults to the values passed to `--source-map`. See
[the uglifyJS options](https://github.com/mishoo/UglifyJS2#user-content-usage). 
I didn't want to commit an entire rebuild of `dist` for a one line fix, but if anything, `dist/async.min.js` can be manually edited to change `//# sourceMappingURL=dist/async.min.map` to `//# sourceMappingURL=async.min.map` before the next rebuild.
Fixes #1117

Fixes #1117

---

README.md
lib/autoInject.js
mocha_test/autoInject.js

autoInject now takes a composite results object again, rather than injecting them.

Revert injection of results in the final callack to autoInject.

---

README.md

Updated documentation of `during` in followup of #1121

Updated description of during #1121

---

lib/priorityQueue.js
mocha_test/priorityQueue.js
mocha_test/queue.js

Related #1131 
The `saturated` test case might need to be added.

fix `priorityQueue`

---

README.md

This might forestall some issues opened while we work on the docs site.  Also might save lots of time for people accidentally reading the new docs and using an old version.

Call out 2.0 breaking changes inline in readme

---

README.md
lib/retry.js
mocha_test/retry.js

Allow interval to be specified as a function(retryCount) : int so users can have exponential backoffs, etc.
#1001

Allow custom retry interval

---

lib/internal/queue.js
lib/queue.js
mocha_test/queue.js

Allowing you to implement things like error logging and task retries more easily, like so:
```javascript
var q = async.queue(function(task, callback) {
console.log('Oops.');
callback(new Error('I fail every time'));
});
q.error = function(error, task) {
if (task.retries == null) task.retries = 0;
task.retries++;
if (task.retries < 3) {
q.push(task);
} else {
console.log('This isnt working...');
}
};
q.push({foo: 'bar'});
```

Add optional error handler to queues

---

lib/index.js
lib/internal/map.js
lib/map.js
lib/mapValues.js
lib/mapValuesLimit.js
lib/mapValuesSeries.js
mocha_test/map.js
mocha_test/mapValues.js

WIP. Closes #1157.
I might add `mapKeys` and family later, but I can't contrive an example use-case where you'd need to map the keys of an object asynchronously.

Mapping over Objects

---

README.md

Anchor tags cannot be self-closing. GitHub corrects it, but [npm](https://www.npmjs.com/package/async#race) doesn't:

fix race() anchor in readme

---

README.md

I got confused for a little bit when I read the quick examples and saw that there was no callback in each of the `.parallel()` and `.series()` functions. So I thought others might also get confused, and added the `callback` parameter to the quick examples.

add callbacks to quick examples

---

lib/asyncify.js
mocha_test/asyncify.js

Code to reproduce the bug:
```javascript
const async = require('async');
const i_return_a_promise = () => Promise.resolve("Hello");
const fn = async.asyncify(i_return_a_promise);
var _count = 0;
fn((err) => {
console.log("CB CALL #%d", ++_count, err);
throw new Error("D:");
});
```
This code will print out:
```
CB CALL #1 null
CB CALL #2 [Error: D:]
```
This is because `.then` on a promise will catch errors, and return a rejected promise, which would then be caught by the `.catch` code, calling the callback twice. This PR fixes that behavior by handling both the resolve case and the rejection case in the `.then` handler.

Callback can be called twice in asyncify when using promises.

---

mocha_test/asyncify.js

This cleans up the no-op unhandledRejection listener that is attached to the process, so that future tests will correctly report unhandledRejections, should they happen.

Remove unhandled rejection listener after asyncify tests are complete

---

lib/autoInject.js
mocha_test/autoInject.js

This is a patch to fix the current `parseParams` method, in order to work with the new ES6 Method Shorthand type: http://es6-features.org/#MethodProperties, and also the `default` value to work (it's being stripped in parse)
Parser needed to be modified in order to work with:
* defaults. Eg.: `function (dependency = [], cb){ ... }`
* Method shorthand. Eg.: `autoInject({ methodName (someDependency, cb){}, ... }
Also, the validation of `autoInject task functions require explicit parameters` had to be removed, since shorthand methods do not show up with `length > 0`.
This was done because I see a great advantage in using the method shorthand with defaults, to improve readability. Take this example:
```
async.autoInject({
forgetTo (callback){
callback(true);
},
dont: (forgetTo, callback) => { …
```

Allow use es6 object method shorthand in autoInject

---

lib/auto.js
lib/internal/DoublyLinkedList.js
lib/internal/queue.js
lib/priorityQueue.js
mocha_test/queue.js

A linked list is a more optimal method to keep track of a stack of tasks as we can end up mutating the `tasks` very frequently. The previous solution could have been further optimized to avoid several splices (i.e. doing 1 splice instead of n in several scenarios), though a linked list solution should generally be more performant.
/cc @aearly 
Fixes #756

Implment queues using DLLs

---

lib/internal/queue.js

Applies some JIT  optimizations for arguments and avoids iterating the entire worker set. Then just uses the idle helper because thats what its there for :)

Optimize queue processing

---

lib/doDuring.js
lib/doWhilst.js
lib/during.js
lib/whilst.js
mocha_test/during.js
mocha_test/until.js
mocha_test/whilst.js

Fix test function arguments for whilst/until/during

---

mocha_test/parallel.js
mocha_test/series.js
mocha_test/waterfall.js
package.json

Do not run sub-context tests under nyc.  nyc uses a separate contex to track code, so tests using a separate context fail under nyc with errors like the following:
1) parallel parallel call in another context:
ReferenceError: __cov_GLCSDG93mVWqRnbTQi1ISfasEto is not defined
at evalmachine.<anonymous>:1:16
at evalmachine.<anonymous>:1:569
at ContextifyScript.Script.runInNewContext (vm.js:18:15)
at Object.exports.runInNewContext (vm.js:49:17)
at Context.<anonymous> (mocha_test/parallel.js:3:954)
This commit also removes the redundant `&& nyc report` from the end of the npm coverage script (nyc outputs the report by default).
fixes #1225

Fix nyc/code-coverage testing

---

CHANGELOG.md
lib/retry.js
mocha_test/retry.js

Also adds some coverage for retry simple case where task resolves instantly

Retry should pass all of the resolve arguments to the callback

---

lib/internal/eachOfLimit.js

Although I made a couple micro perf optimizations (avoiding a couple extra function calls) there are no real changes to performance.
I did find another minor optimization was to aggressively set the `iterateeCallback` to null when done (in which case we could also kill the done variable)

Minor cleanups to eachOfLimit

---

lib/each.js
lib/eachOf.js
lib/every.js
lib/filter.js
lib/map.js
lib/parallel.js
lib/reject.js
lib/some.js
mocha_test/eachOf.js

https://github.com/caolan/async/pull/847 was a valuable change to the code base in which we definetely cleaned things up.
In this PR I want to add a special case, where we consider the array case separate from the generic case. I think this is important as I believe the parallel cases of `each`, `eachOf`, `map`, `filter`, etc when provided arrays are one of the hottest paths in the library. Therefore, I have decided to optimize parallel array processing for all methods which use `eachOf` for the array case and defer to the `eachOfLimit` implementation for objects and iterators.
[On my run of the relevant benchmarks, the suite ran 27.4% faster](https://github.com/caolan/async/files/374892/perf.txt)
/cc @aearly @charlierudolph

Fast path eachOf array case

---

lib/internal/iterator.js

This just separates the types of iterators out into atomic functions instead of handling all types in one spot

Make iterator more prone to JIT optimizations

---

support/jsdoc/theme/static/styles/jsdoc-default.css
support/jsdoc/theme/tmpl/method.tmpl

@megawac this turned out to be a really easy fix, sorry for the delay.
I added the alias right before the parameters:
Just in case we add multiple alias for a function in the future, I tested it for that too:
```js
* @alias forEach, anotherAlias
```
Let me know if anything needs to be changed. Thanks.

added alias documentation, fixes #1251

---

lib/internal/queue.js
lib/priorityQueue.js
lib/race.js
perf/suites.js

Figure there is no reason to not write these simple loops our selves.
```
Latest tag is  v2.0.1
Comparing v2.0.1 with current on Node v6.2.2
--------------------------------------
queue(1000) v2.0.1 x 345 ops/sec ±0.80% (30 runs sampled), 2.90ms per run
queue(1000) current x 352 ops/sec ±0.90% (30 runs sampled), 2.84ms per run
current is faster
--------------------------------------
queue(30000) v2.0.1 x 9.39 ops/sec ±3.62% (18 runs sampled), 106ms per run
queue(30000) current x 10.52 ops/sec ±2.89% (20 runs sampled), 95.1ms per run
current is faster
--------------------------------------
queue(100000) v2.0.1 x 2.53 ops/sec ±11.46% (6 runs sampled), 396ms per run
queue(100000) current x 3.05 ops/sec ±8.64% (6 runs sampled), 328ms per run
current is faster …
```

Unroll simple loop abstractions

---

lib/retry.js
mocha_test/retry.js
mocha_test/retryable.js

* add filter option to `retry()` and `retryable()` to allow for error filtering and control of retry flow. Resolves #1256.
* Added comment regarding the new option. Do I need to run the script to update the generated documentation?
* The new option is called `errorFilter`.
* Added tests. Lint and all existing tests pass when I run with `npm test`.
Fixes #1256 - megawac

add filter option to retry() and retryable(). PR for #1256.

---

intro.md

Under Quick Examples the `async.parallel()` example is missing the closing parenthesis. This PR just adds the parenthesis.

Adding closing parenthesis to parallel example.

---

lib/whilst.js

The docs are a little confusing here, since they refer to `fn`, but the signature names that argument `iteratee`. I'm just clarifying it here...
Signed-off-by: Dave Henderson <dhenderson@gmail.com>

Fixing inconsistency in whilst jsdoc

---

support/jsdoc/jsdoc-custom.js
support/jsdoc/jsdoc-fix-html.js
support/jsdoc/theme/static/styles/jsdoc-default.css
support/jsdoc/theme/tmpl/layout.tmpl

I just wanted a second opinion on this PR because I had to change the ids of the method sections in the body for scroll-spy to work. I just had to remove the `.` in front the ids (`.eachSeries` vs `eachSeries` now). This means that potentially old links to methods in the docs will just point to the top of the old page. I added some js that should minimise this, it replaces the hash in the link with the hash with the `.` removed. It should direct users to the correct method.
I think the ids are a result of the way minami generates them. Its something I should've changed initially when creating the docs. Sorry about that.
Also, to get scroll-spy to work, I had to rearrange some of the HTML/CSS, but from what I can see, everything looks the same as before. I have a live demo on my fork: …

added scroll-spy behaviour (fixes #1289)

---

lib/mapValues.js
lib/mapValuesLimit.js
lib/mapValuesSeries.js

This replaces "array" with "object" (looks like it was likely a copy/paste error from when these docs were originally brought over from `.map()`), and rephrases the sentence accordingly.  I also normalized an occurrence of "result" vs. "results" to match.
> *NOTE:* I did not yet go through and do the same to `.mapValuesLimit()` and `.mapValuesSeries()` in this commit.  I'm happy to take care of that in this PR, but it's purely a matter of copy and pasting the relevant comments.

docs: fix typo in expected result for`mapValues()`

---

lib/internal/breakLoop.js
lib/internal/createTester.js
lib/internal/eachOfLimit.js
mocha_test/detect.js
mocha_test/every.js
mocha_test/some.js

Add the ability to short circuit `eachLimit` and `eachSeries` loops internally. Break loops when value is determined for some, every and detect/find
Fixes #1293

Short circuit loops completely for some,every,detect when ready

---

lib/apply.js
lib/auto.js
lib/autoInject.js
lib/compose.js
lib/constant.js
lib/doDuring.js
lib/doWhilst.js
lib/internal/applyEach.js
lib/internal/consoleFunc.js
lib/internal/initialParams.js
lib/internal/map.js
lib/internal/parallel.js
lib/internal/queue.js
lib/internal/reject.js
lib/internal/rest.js
lib/internal/setImmediate.js
lib/memoize.js
lib/reflect.js
lib/seq.js
lib/waterfall.js
lib/whilst.js

Saves 800 bytes on min.js
fyi _baseRest imports a bunch of string manipulation code to manage setting `func.toString` on the output function

Cleanup some of the dependency imports

---

dist/async.js
lib/internal/applyEach.js
lib/internal/consoleFunc.js
lib/memoize.js
lib/retryable.js
lib/seq.js

removed unnecessary arrays
Array.prototype.concat can be used like so
`[1,2,3].concat(4)`
you don't need to do
`[1,2,3].concat([4])`

remove unnecessary arrays

---

lib/auto.js
mocha_test/auto.js

Hi, I'm not sure if there were specific guidelines to go through before submitting a PR, so apologies if I've missed a step. Now on to the PR:
We've been making use of `async.autoInject` as a light dependency injection framework, and whenever we'd make a mistake in a tasks dependencies we'd end up with a time-consuming task to track down what dependency `async` was failing on, because the error message wasn't giving enough to go on.
This PR simply adds the actual failed dependency to the error message to trivialize the work of tracking down missing dependencies.

Print the name of the actual missing dependency in `async.auto`

---

lib/detect.js
lib/detectLimit.js
lib/detectSeries.js
lib/eachOf.js
lib/every.js
lib/everyLimit.js
lib/internal/createTester.js
lib/some.js
lib/someLimit.js

Most functions in `async` that have `*Series` & `*Limit` versions use `doParallel`, `doParallelLimit` and `doLimit` in their implementation. This PR modifies `internal/createrTester` to be compatible with those functions, which allows `detect`, `every`, and `some` to follow the same pattern.

standardize detect, every, and some implementations to use doParallel & equivalents

---

lib/groupBy.js
lib/groupByLimit.js
lib/groupBySeries.js
lib/index.js
lib/map.js
mocha_test/groupBy.js

My attempt at implementing groupBy for #1348 (and I guess #214). This is my first feature implementation for `async`, so feedback is greatly appreciated. 
I may have been a little excessive with the testing, as I ported a lot of the generic tests (like ensuring `groupByLimit` follows the concurrency limit) from `mocha_test/map.js`, while including a few specific `groupBy` tests. Also, the example I used for the docs isn't that great as I couldn't really come up with anything concise but illustrative. I'd like to change it before merging, if anyone has any ideas.

[#1348] initial groupBy implementation

---

lib/transform.js
mocha_test/filter.js
mocha_test/transform.js

The documentation suggests that both the `accumulator` and `callback` arguments to transform is optional. 
(https://caolan.github.io/async/docs.html#transform) 
However, if both are left out (and transform therefore is called with only 2 arguments), transform crashes with a `iteratee is not a function` exception. 
By changing the equality check to a less than check, the transform function support the use-case where only 2 arguments are passed.

Make async.transform actually support 2 arguments

---

lib/parallel.js

How to continue *parallel* processing in case of a failing task seems to be a frequently asked question. It was mentioned in several issues:
- https://github.com/caolan/async/issues/334
- https://github.com/caolan/async/issues/675
- https://github.com/caolan/async/issues/798
- https://github.com/caolan/async/issues/942
Adding a hint to the documentation might help users of the library to find out about the answer to this question.

Add a hint to `reflect` in the documentation of `parallel`

---

lib/index.js
lib/tryEach.js
mocha_test/tryEach.js

This adds async.tryEach which fixes what was requested in #687. I needed something with similar requirements. My use case was that I needed to get some data, which I could get it from 3 websites(with slightly different code for each) but sometimes they go down randomly.
The name might be reconsidered. We can't use `try` because it's a reserved word. I couldn't think of anything better.
You guys might want to also review the documentation, English is not my first language.
As you can see I wrote tests covering most cases, and the coverage is 100% for the file.

Add async.tryEach

---

lib/internal/DoublyLinkedList.js
lib/internal/queue.js
lib/queue.js
mocha_test/linked_list.js
mocha_test/queue.js

Closes #1391 .
Adds a `remove` function to queues.  Without it, there is no way to arbitrarily remove items from the queue.  In Async 1.x and below, the `tasks` list was just an array, so you could splice as you needed.  This adds a `filter` function to the `DoublyLinkedList` class that is used by `q.remove`.
I also added some unit tests for `DLL` itself.  I also noticed that the prior implementation of `empty` could cause a memory leak.  I think the lingering chain of `prev`/`next` references could fool GC and keep the objects around.

queue.remove()

---

intro.md

both jam and component are deprecated reading their GitHub readmes.

docs(intro): remove non relevant pkg managers

---

lib/asyncify.js
mocha_test/asyncify.js

If asyncify wraps a function returning promises, the callback will be executed as part of the promise’s `.then()` method.
This means that any error thrown from that method will be silenced, and lead to a “unhandled promise rejection” warning in modern engines.
Usually, we want these errors to be visible, and even crash the process.
I’d like to add a test, but there doesn’t seem to be a good way to do it, especially for both node.js and browsers.

[asyncify] Make errors in callbacks throw globally

---

mocha_test/queue.js

According to code in queue.js
``` javascript
length: function () {
return q._tasks.length;
}
```
It may be better to use `q.length()` rather than `q._tasks.length`

may be it's better to use the length method

---

lib/timeout.js
mocha_test/timeout.js

Previously, the scoping of the `timedOut` variable in `timeout` meant that if any call to wrapped function timed out, any subsequent calls would also give a `ETIMEDOUT` error. This PR fixes that by moving the variables down one scope, so they are reinitialized each call. As a side benefit, it also lets the wrapped function be passed to functions such as `async.forEach`.

Allow functions wrapped in `timeout` to be called multiple times (fixes #1418)

---

lib/internal/queue.js
mocha_test/cargo.js
mocha_test/queue.js

Aligns `q.workersList()` and `cargo.workersList()` with the [docs](https://caolan.github.io/async/docs.html#QueueObject).
`workersList()` is not really relevant in the context of `async.cargo`, as there will only be 1 worker running at a given time, but I would prefer to keep the behavior consistent between it and `queue`.

ensure q.workersList() contains items being processed [fixes #1428]

---

lib/concatLimit.js
lib/index.js
mocha_test/concat.js

Adds the elusive `concatLimit`.

add concatLimit [fixes #1426]

---

Makefile

I haven't worked with make files too much, so I just wanted a second set of eyes before merging. Thanks!

update Makefile to include source map in build dir [fixes #1452]

---

lib/internal/queue.js

Hi,
I had some performance issues when using `async.cargo` with large number of tasks (batches of 10k). Changing `splice(0, 1)` to `shift()` improved it dramatically (for a batch of 10k it removed ~3 seconds from each batch). 
For some reason I wasn't able to reproduce it using an example. Maybe it depends on the memory state of the process. From a simple [benchmark](https://jsperf.com/remove-first-element-from-array/4) here you can see shift is much faster than splice (I checked on Safari, Chrome & Firefox on MacOS)

Use shift instead of splice (when possible) in queue

---

lib/internal/eachOfLimit.js
mocha_test/eachOf.js

`eachOfLimit` throws a `RangeError: Maximum call stack size exceeded` when the collection is too big and the iteratee is synchronous.
The usual workaround is to use `setImmediate(next)` or [http://caolan.github.io/async/docs.html#ensureAsync](http://caolan.github.io/async/docs.html#ensureAsync).
I have a data analysis program. The `setImmediate(next)` workaround made the whole program slow when there are few new data to analyse.
With a small modification, it was possible to make the program lasting from minutes to seconds.
Here is an exemple of time duration with and without `setImmediate`
```js
const eachOfLimit = require("async/eachOfLimit");
(function() {
'use strict';
const collection = new Array(Math.pow(1024, 2));
for (let i = 0, len = collection.length; i < len; i++) { …
```

fix "RangeError: Maximum call stack size exceeded"

---

Makefile
README.es.md
support/sync-es-package.js

Hey there! I optimized the library for users who build their browser apps with webpack. [webpack](https://github.com/webpack/webpack) is super-popular in front-end development, so that should be a large percent of browser users.
In my tests with `map`/`parallel` methods, the library size dropped from 28 to 12 minified kB (−57%). Here’s the repo if you want to reproduce: [iamakulov/async-optimization-repro](https://github.com/iamakulov/async-optimization-repro)
_This is a part of my performance consulting. I help open-source projects (for free) and companies (for money) to optimize the performance of their products: [iamakulov.com/perf-consulting](https://iamakulov.com/pages/perf-consulting/)_
---
**The problem**
Right now, when you import `async` into the app, you import all the methods …

Optimize the library for webpack users

---

lib/memoize.js
mocha_test/memoize.js

fixes #1465 
This one is debatable if we want to change behaviour in 2.x. I think it makes sense to however could be swayed otherwise. Thoughts @aearly?

Don't memoize results that had an error

---

test/memoize.js

It is related to https://github.com/caolan/async/pull/1466
I realized that the test case doesn't test the changes.
The function memoizes the results using the first argument by default.
So `5` is the different key, memo won't be used. :)

Fix a memoize test case

---

intro.md
lib/auto.js
lib/doDuring.js
lib/doWhilst.js
lib/during.js
lib/eachOf.js
lib/forever.js
lib/internal/eachOfLimit.js
lib/retry.js
lib/tryEach.js
lib/waterfall.js
lib/whilst.js
test/auto.js
test/during.js
test/eachOf.js
test/forever.js
test/parallel.js
test/retry.js
test/until.js
test/waterfall.js
test/whilst.js

Closes #1064 
This allows you to signal that you have exited early from an async flow by `callback(false)` --- calling back with `false` as the error.  All further callbacks will be ignored, and the final callback will not be called.  This is handy to avoid a subtle memory leak when you exit early.

feat: Canceling flows

---

lib/internal/eachOfLimit.js
lib/internal/queue.js
test/concat.js
test/each.js
test/eachOf.js
test/groupBy.js
test/map.js

limits of less than 1 are now an error

---

lib/internal/DoublyLinkedList.js
lib/internal/queue.js
lib/queue.js
test/queue.js

feat: Iterable queues

---

lib/concat.js

Concat function, since v2.5.0, returns back array results in the original order.

Updated outdated documentation for Concat

---

intro.md

Thanks for the great documentation

Small typo :)

---

README.md

`--save` is on by default as of [npm 5](https://blog.npmjs.org/post/161081169345/v500), so `npm install aphrodite` is functionally equivalent to `npm install --save aphrodite` now

--save no longer needed

---

lib/concatLimit.js
lib/groupByLimit.js
lib/internal/createTester.js
lib/internal/filter.js
lib/mapValuesLimit.js
lib/sortBy.js
lib/tryEach.js
test/applyEach.js
test/autoInject.js
test/compose.js
test/concat.js
test/detect.js
test/each.js
test/every.js
test/filter.js
test/groupBy.js
test/map.js
test/mapValues.js
test/parallel.js
test/reduce.js
test/retryable.js
test/seq.js
test/series.js
test/some.js
test/sortBy.js
test/times.js
test/transform.js
test/tryEach.js

This PR ensures that method pass the `err` onto `eachOfLimit`, so that they can be canceled properly. The one method I'm not quite sure about is `tryEach`. I'm assuming that since `retry` is cancelable, `tryEach` should be too?
Sorry if I went a little overboard with the tests, I ended up going down a rabbit hole :sweat_smile:. For the tests, I was trying to follow the coding style of the encompassing file, which is why some of the descriptions and styles vary. I figured it would be better to keep consistent logging and for future maintenance.

Fixes #1582

---

lib/priorityQueue.js
test/priorityQueue.js

Priority queue should check if the underlying queue is idle before draining.
Currently the priorityQueue drains if an empty array of tasks is pushed even if other tasks are processing.

fix: priorityQueue drains while items still pending

---

intro.md

"As of npm 5.0.0, installed modules are added as a dependency by default, so the --save option is no longer needed. The other save options still exist and are listed in the documentation for npm install."
https://stackoverflow.com/a/19578808/142358

Remove --save option as it isn't required anymore

---

lib/eachSeries.js
lib/internal/applyEach.js
test/applyEach.js
test/es2017/asyncFunctions.js
test/es2017/awaitableFunctions.js
test/priorityQueue.js

Fixes #1228 , making it more type-able.
This reduces the utility of `applyEach`, though.
I'm almost in favor of removing the whole method.   I couldn't find any examples of it being used in the wild, and has always been a strange method.

BREAKING CHANGE: remove partial application feature of applyEach

---

lib/cargo.js
lib/eachSeries.js
lib/internal/queue.js
lib/queue.js
test/cargo.js
test/cargoQueue.js
test/es2017/asyncFunctions.js
test/es2017/awaitableFunctions.js
test/priorityQueue.js
test/queue.js

Closes #1586 
This changes the queue API a bit, allowing queue events to be awaited, as well as the results for an individual task.  You can now do:
```js
var q = async.q(async fn (task) { /* ... */ }, 10)
await q.push(task) // awaits until task has been processed
await Promise.all(q.push([1, 2, 3])) // awaits for all tasks to be processed
q.push(5) //set and forget, this won't reject if an error happens
await queue.drain() // probably the most useful thing to come out of this change
```

BREAKING CHANGE: awaitable queues

---

README.es.md
README.md

Added badges for Pipelines and for each platform in a table.
**Note:** Windows and Linux builds are red due to the lack of COVERALLS_REPO_TOKEN variable.
**Note 2:** libhive.com SSL cert is wrong/expired. I'm ignoring it.
See badges preview: https://github.com/pablonete/async/blob/azure-pipelines-badges/README.md

Azure pipelines badges

---

dist/async.js
docs/v2/scripts/async.js
docs/v3/scripts/async.js
lib/groupBySeries.js

There is a small typo in dist/async.js, docs/v2/scripts/async.js, docs/v3/scripts/async.js, lib/groupBySeries.js.
Should read `whose` rather than `whoses`.

docs: Fix simple typo, whoses -> whose

---

lib/priorityQueue.js

This applies the same technique that was done for queue in PR #1448 to priorityQueue. The change prevents multiple calls to setImmediate for queue processing that originate from calls to push on the same tick. The added overhead of the change is fairly negligible -- one variable assignment and two conditions. 
```
$ perf/benchmark.js --grep priorityQueue
Latest tag is  v3.2.0
Comparing v3.2.0 with current on Node v12.13.1
--------------------------------------
priorityQueue(10) v3.2.0 x 16,503 ops/sec ±2.79% (27 runs sampled), 0.0606ms per run
priorityQueue(10) current x 17,979 ops/sec ±4.99% (28 runs sampled), 0.0556ms per run
current is faster
--------------------------------------
priorityQueue(100) v3.2.0 x 4,261 ops/sec ±1.90% (28 runs sampled), 0.235ms per run
priorityQueue(100) …
```

priorityQueue: Prevent same tick setImmediate

---

docs/v3/scripts/async.js
lib/reduce.js
lib/reduceRight.js

Fixind the typo issue https://github.com/caolan/async/issues/1747

fixing the grammar in documentation

---

lib/internal/setImmediate.js
test/cargoQueue.js

Since `setTimeout` get throttled by browsers and `setImmediate` doesn't actually exist in any browsers, we should use `queueMicrotask` which works very similarly to the intention of `setImmediate`.
I have an app that uses stanza.io which relies on async's `priorityQueue`. It was found that `priorityQueue` is getting throttled because of its use of `setTimeout(fn, 0)`. Most browsers support `queueMicrotask`, but for those who don't, we will fallback.

use queueMicrotask instead of setTimeout in browsers to avoid browser throttling

---

lib/map.js

Fix(docs): use plural `callbacks` word in `lib/map.js`

---

lib/seq.js
package-lock.json
package.json
perf/suites.js
support/jsdoc/jsdoc-fix-html.js
support/jsdoc/theme/publish.js
test/auto.js

When installing all dependencies then it yields some deprecation warnings. some packages wasn't even being used.
Where going to fix some of it but ended up doing something else instead.
---
Where thinking of removing `fs-extra` also but though if i should ask first...
it seems to only be used in development to fix some docs and reading some files
i where thinking that it wouldn't be so bad if it used nodes native `fs` after all 
And b/c it's dev only and mostly one time thing. i think it wouldn't be nice to use the sync api instead to remove some "callback-hell" stuff and avoid the need of async and or promises.
the sync methods are faster after all but they are blocking...

Housekeeping

---

.github/workflows/ci.yml

Was hitting some macOS issues that I thought might be coming from here, so i thought it might be good to add back a full test matrix.
I left in the Azure DevOps CI, but only added in 12+ node versions since Node 10 is EOL

ci: setup GitHub Actions

---

lib/autoInject.js
test/autoInject.js

Unforunately, cdfb4917e6028c8f966276d6e792018c7fd2ae3c introduced issues
with certain edge cases for comments. Fixing the edge case in the
regular expression is likely to reintroduce the issue that commit was
addressing. This change replaces the regular expression entirely with
a function that iterates through the string instead of regular
expressions.

fix: address edge case in comment stripping

---

lib/detect.js
lib/detectLimit.js
lib/detectSeries.js
lib/race.js
lib/waterfall.js

Hey! It's been a while since I contributed to the repo, so I thought I would start with a couple of quick doc updates.
This PR adds the missing return definitions for `race` and `waterfall` and updates the `detect*` docs to match the style of all the other functions.

docs: add missing return definitions for awaitable functions [fixes #1777]

---

.github/dependabot.yml
.github/workflows/ci.yml

Now the CI is testing across platforms, Dependabot can be used to start testing dependdency updates

chore: add Dependabot for version updates

---

lib/internal/iterator.js
mocha_test/mapValues.js

(cherry picked from commit e1ecdbf79264f9ab488c7799f4c76996d5dca66d)
Conflicts:
lib/internal/iterator.js
test/mapValues.js
NOTE(mriedem): The conflicts are due to:
- e4751178540a3c6e64598b93977481ec599704d2 for iterator.js;
resolution was trivial
- bd86f42a7d71552d9a502b50235ffc090a1b4a98 for mapValues.js;
resolution was just copying the test change into the old
test file before it was moved
This is a 2.x series backport for
https://nvd.nist.gov/vuln/detail/CVE-2021-43138.

Fix prototype pollution vulnerability

---

lib/internal/queue.js
lib/priorityQueue.js
test/es2017/awaitableFunctions.js
test/priorityQueue.js
test/queue.js

This PR updates the `priorityQueue` behaviour to match the `queue` implementation:
* better supports promises in `priorityQueue` (see #1725).
* supports `pushAsync` and removes `unshiftAsync`.
* fixes a bug where `drain` wasn't being called when an empty task was pushed.
* eliminates duplicate code by keeping all of the `queue` logic in `queue`. The one issue with this is it now iterates over the `tasks` twice, once in `priorityQueue` and once in `queue`. Let me know if there's a better way you can think of.
I also added a few tests from `queue` to `priorityQueue` to make sure the functionality matches.

update priorityQueue functionality to match queue [fixes #1725]

---

.github/workflows/ci.yml

GitHub asks developers to define workflow permissions, see https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/ and https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token for securing GitHub workflows against supply-chain attacks.
The Open Source Security Foundation (OpenSSF) [Scorecards](https://github.com/ossf/scorecard) also treats not setting token permissions as a high-risk issue. 
This PR adds minimum token permissions for the GITHUB_TOKEN using https://github.com/step-security/secure-workflows. 
This project is part of the top 100 critical projects as per OpenSSF (https://github.com/ossf/wg-securing-critical-projects), so fixing the token permissions to improve …

ci: Add GitHub token permissions for workflow

---

CHANGELOG.md

Seems to have been forgotten for the 3.2.5 release. Keeping the changelog updated is very useful to quickly review what has changed so we don't need to dig around in commit logs.

Update changelog for v3.2.5
